//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace imt_wankeyun_client.Properties {
    using System;
    
    
    /// <summary>
    ///   一个强类型的资源类，用于查找本地化的字符串等。
    /// </summary>
    // 此类是由 StronglyTypedResourceBuilder
    // 类通过类似于 ResGen 或 Visual Studio 的工具自动生成的。
    // 若要添加或移除成员，请编辑 .ResX 文件，然后重新运行 ResGen
    // (以 /str 作为命令选项)，或重新生成 VS 项目。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   返回此类使用的缓存的 ResourceManager 实例。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("imt_wankeyun_client.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   使用此强类型资源类，为所有资源查找
        ///   重写当前线程的 CurrentUICulture 属性。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   查找类似 title：value  
        /// 的本地化字符串。
        /// </summary>
        internal static string MdTableContent {
            get {
                return ResourceManager.GetString("MdTableContent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似于 (图标) 的 System.Drawing.Icon 类型的本地化资源。
        /// </summary>
        internal static System.Drawing.Icon offline {
            get {
                object obj = ResourceManager.GetObject("offline", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        
        /// <summary>
        ///   查找类似于 (图标) 的 System.Drawing.Icon 类型的本地化资源。
        /// </summary>
        internal static System.Drawing.Icon online {
            get {
                object obj = ResourceManager.GetObject("online", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        
        /// <summary>
        ///   查找类似 &lt;tr&gt;
        ///&lt;th style=&quot;color:#fff;
        ///    text-shadow:1px 1px 1px #568F23;
        ///    background-color:#9DD929;
        ///    border:1px solid #93CE37;
        ///    border-right:3px solid #9ED929;
        ///    padding:0px 10px;
        ///    background:-webkit-gradient(
        ///        linear,
        ///        left bottom,
        ///        right top,
        ///        color-stop(0.02, rgb(158,217,41)),
        ///        color-stop(0.51, rgb(139,198,66)),
        ///        color-stop(0.87, rgb(123,192,67))
        ///        );
        ///    background: -moz-linear-gradient(
        ///        left bottom,
        ///        rgb(158,217,41) 2 [字符串的其余部分被截断]&quot;; 的本地化字符串。
        /// </summary>
        internal static string TableContent {
            get {
                return ResourceManager.GetString("TableContent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 &lt;/table&gt; 的本地化字符串。
        /// </summary>
        internal static string TableEnd {
            get {
                return ResourceManager.GetString("TableEnd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 &lt;table style=&quot;font-family: &quot;Trebuchet MS&quot;, sans-serif;
        ///    font-size: 16px;
        ///    font-weight: bold;
        ///    line-height: 1.4em;
        ///    font-style: normal;
        ///    border-collapse:separate;&quot;&gt; 的本地化字符串。
        /// </summary>
        internal static string TableStart {
            get {
                return ResourceManager.GetString("TableStart", resourceCulture);
            }
        }
    }
}
